### ISSUE TITLE
BTC-INR value is returning a wrong value

### ISSUE THREAD

**Issue by srhr17** [lagerfeuer/cryptocompare#38]
{'BTC': {'INR': 0.04166}}
Return a wrong BTC-INR value

**Comment by lagerfeuer** [comment]
I don't know what CryptoCompare is doing with INR, but it genuinely seems like something erroneous is happening. If you check the request at https://min-api.cryptocompare.com/data/pricemulti?fsyms=BTC&tsyms=EUR,USD,INR (which is all my library does), INR comes back from the API with a false value. The values for USD and EUR are correct, however.

Funny enough, using the historical price endpoint, it works: https://min-api.cryptocompare.com/data/pricehistorical?fsym=BTC&tsyms=USD,EUR,INR&ts=1597896000 (where `ts` is the timestamp for 20th August 2020).

As a workaround, I suggest you use the historical price endpoint instead of the normal price endpoint, meaning you should change
```python
cryptocompare.get_price('BTC', curr='INR')
```
to
```python
from datetime import datetime
cryptocompare.get_historical_price('BTC', 'INR', datetime.now())
```

Closing this for now since I can't do anything about it, hope this helps.
