### ISSUE TITLE
Get The number of cryptos label:enhancement 

### ISSUE THREAD

**Issue by Arkadio918** [lagerfeuer/cryptocompare#45]
now i need to do this: Pull out a request for all the coins on the list then print it's length 
```
list=cryptocompare.get_coin_list(format=True)
print(len(list))
```
i wont something lees invasive like: Guste pool out the length 
```
Number=cryptocompare.get_coin_list_number()
print(Number)
```

PS: if there is all ready a way i'm sorry

**Comment by lagerfeuer** [comment]
This is not something I can change, since Cryptocompare does not expose an API call like that, from what I can tell.

Please refer to the official documentation at https://min-api.cryptocompare.com/documentation

If you find something, let me know, but all I can see is the _all coins_ API call.

Closing for now unless you find something.
