### ISSUE TITLE
Getting all data for a coin

### ISSUE THREAD

**Issue by farzinaa** [lagerfeuer/cryptocompare#50]
Hi, 
I was wondering if there is a way to set the limit in historical data to ALL or MAX. 
eg: 
data = get_historical_price_minute('BTC', 'EUR', limit=ALL/MAX, exchange='CCCAGG', toTs=datetime.datetime.now())

I currently get "limit is larger than max value" when I use a large number for the limit. 

Thanks.

**Comment by lagerfeuer** [comment]
Hi @farzinaa 

For this, I'd have to quote the [documentation](https://min-api.cryptocompare.com/documentation?key=Historical&cat=dataHistoday) from CryptoCompare. `limit` can be quite odd at times.
Here's the relevant part:

> The number of data points to return. If limit * aggregate > 2000 we reduce the limit param on our side. So a limit of 1000 and an aggerate of 4 would only return 2000 (max points) / 4 (aggregation size) = 500 total points + current one so 501. [ Min - 1] [ Max - 2000] [ Default - 30]

As far as I can tell, this limit is in place for all operations that have the `limit` parameter.
I have no intentions of adding another parameter or allowing `ALL` or `MAX` because I feel it hides too much.

**Comment by farzinaa** [comment]
Thanks
